apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: samtalestotte-arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-teamia-utvikling'
      prependText: '<!here> | '
  alerts:
    - alert: Applikasjon nede
      expr: sum(up{app="samtalestotte-arbeidsgiver", job="kubernetes-pods"}) == 0
      for: 30s
      description: "samtalestotte-arbeidsgiver er nede"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.adeo.no/d/MwhvlzSMz/team-ia-samledashboard"
