apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtalestotte-arbeidsgiver
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  env:
    - name: AUTH_URL
      value: https://www.dev.nav.no/person/nav-dekoratoren-api/auth
    - name: MINSIDE_ARBEIDSGIVER_URL
      value: https://min-side-arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver
    - name: FOREBYGGE_FRAVAR_URL
      value: https://forebygge-fravar.intern.dev.nav.no/forebygge-fravar
    - name: SAMTALESTOTTE_URL
      value: https://samtalestotte.intern.dev.nav.no/samtalestotte
    - name: GRAFANA_AGENT_COLLECTOR_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: IA_TJENESTER_METRIKKER_HOSTNAME
      value: ia-tjenester-metrikker.intern.dev.nav.no
    - name: IA_TJENESTER_METRIKKER_AUDIENCE
      value: "dev-gcp:arbeidsgiver:ia-tjenester-metrikker"
  ingresses:
    - https://samtalestotte.intern.dev.nav.no/samtalestotte
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
  liveness:
    path: /samtalestotte/api/isAlive
    initialDelay: 10
  readiness:
    path: /samtalestotte/api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.ekstern.dev.nav.no
        - host: ia-tjenester-metrikker.intern.dev.nav.no