apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtalestotte-arbeidsgiver-mock
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  env:
    - name: AUTH_URL
      value: https://www.dev.nav.no/person/nav-dekoratoren-api/auth
    - name: MINSIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/min-side-arbeidsgiver
    - name: FOREBYGGE_FRAVAR_URL
      value: https://forebygge-fravar.ekstern.dev.nav.no/forebygge-fravar
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/samtalestotte
    - name: PROD_URL
      value: https://arbeidsgiver.nav.no/samtalestotte
  ingresses:
    - https://arbeidsgiver.ekstern.dev.nav.no/samtalestotte
  liveness:
    path: /samtalestotte/api/isAlive
    initialDelay: 10
  readiness:
    path: /samtalestotte/api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.ekstern.dev.nav.no
