apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtalestotte-arbeidsgiver
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  env:
    - name: ENVIRONMENT
      value: labs-gcp
    - name: NEXT_PUBLIC_MINSIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver
    - name: NEXT_PUBLIC_FOREBYGGE_FRAVAR_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar
    - name: NEXT_PUBLIC_SAMTALESTOTTE_URL
      value: https://arbeidsgiver.labs.nais.io/samtalestotte
  ingresses:
    - https://arbeidsgiver.labs.nais.io/samtalestotte
  liveness:
    path: /samtalestotte/api/isAlive
    initialDelay: 10
  readiness:
    path: /samtalestotte/api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
