apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtalestotte-arbeidsgiver
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://arbeidsgiver.labs.nais.io/samtalestotte
  liveness:
    path: /samtalestotte/api/isAlive
    initialDelay: 10
  readiness:
    path: /samtalestotte/api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
