apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtalestotte-arbeidsgiver
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  env:
    - name: AUTH_URL
      value: https://www.nav.no/person/nav-dekoratoren-api/auth
    - name: MINSIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver
    - name: FOREBYGGE_FRAVAR_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver.nav.no/samtalestotte
    - name: GRAFANA_AGENT_COLLECTOR_URL
      value: https://telemetry.nav.no/collect
  ingresses:
    - https://arbeidsgiver.nav.no/samtalestotte
  liveness:
    path: /samtalestotte/api/isAlive
    initialDelay: 10
  readiness:
    path: /samtalestotte/api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: dekoratoren.nav.no
        - host: www.nav.no
