name: Build, test and deploy
run-name: Build and deploy || ${{ github.event.head_commit.message }}
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    timeout-minutes: 10
    name: Build, test and push docker image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Push to Google Artifact Registry
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamia
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          salsa: false
    outputs:
      image: ${{ steps.docker-push.outputs.image }}


  deploy-to-dev:
    timeout-minutes: 5
    name: Deploy to dev-gcp
    if: github.ref == 'refs/heads/master'
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev.yaml

  deploy-to-ekstern-dev:
    timeout-minutes: 5
    name: Deploy to dev-gcp (ekstern)
    if: github.ref == 'refs/heads/master'
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/ekstern-dev.yaml

  deploy-to-prod:
    timeout-minutes: 5
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/master'
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod.yaml
