name: Build and deploy master

on: [ push ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

concurrency:
  group: build-deploy-on-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-test-and-build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: |
          docker build . -t ${IMAGE} && docker push ${IMAGE}

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    if: github.ref == 'refs/heads/Migrering_til_ghcr'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/dev-gcp.yaml
          PRINT_PAYLOAD: true
  deploy-to-labs-gcp:
    name: Deploy to labs-gcp
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/uu-icon-title-fix'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/labs-gcp.yaml
          PRINT_PAYLOAD: true
  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/master'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/prod-gcp.yaml
          PRINT_PAYLOAD: true
